version: '3'

services:
  ai_painting:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      - MONGO_HOST=mongo-host
      - MONGO_PORT=27017
      - HOST=0.0.0.0
      - PORT=8080
      - HOST_URL=localhost
      - HTTP_PORT=8000
      - JWT_SECRET=ai_drawing_gallery_secret_key
    restart: always
    command: bash /app/unraid-docker-run.sh
    network_mode: "bridge"

volumes:
  mongo_data: 